--- 
db-server: 
  container_name: db-server
  environment: 
    - ACCEPT_EULA=Y
    - MSSQL_SA_PASSWORD=Bruce1234
    - MSSQL_TCP_PORT=1433
  image: "microsoft/mssql-server-linux:2017-latest"
  networks: 
    - localdev
  ports: 
    - "1400:1433"
networks: 
  localdev: 
    name: localdev
services: 
  main-api: 
    build: CryptoAPI/
    depends_on: 
      - db-server
    networks: 
      - localdev
    ports: 
      - "7000:80"
    restart: always
version: "3"