name: .NET_API_CI

on:
  push: 
    branches: 
      - main

env: 
  SOLUTION_PATH: ./CryptoAPI.sln

jobs: 
  Code-Check: 
    runs-on: ubuntu-latest
    steps: 
      - name: "Checkout Repository"
        uses: actions/checkout@v2
      
      - name: "Initialize CodeQL"
        uses: github/codeql-action/init@v1
        with: 
          languages: csharp
      
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1
      
      - name: "Perform CodeQL Analysis"
        uses: github/codeql-action/analyze@v1

  Build-Testing: 
    runs-on: ubuntu-latest
    needs: Code-Check
    steps: 
      - uses: actions/checkout@v2
        
      - name: "Setup .NET"
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: 3.1.x
   
      - name: "Restore dependencies"
        run: "dotnet restore ${{ env.SOLUTION_PATH }}"
      
      - name: Build
        run: "dotnet build --no-restore ${{ env.SOLUTION_PATH }}" 
     
      - name: Test
        run: "dotnet test --no-build --verbosity normal ${{ env.SOLUTION_PATH }}"
   
  CD-Docker:
    runs-on: ubuntu-latest
    needs: Build-Testing
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Docker Build CD
        run: |
          docker build ./CryptoAPI -t cryptoapi
          
      - name: Docker Push
        run: |
          docker push cryptoapi
