name: .NET_API_CI_CD

on:
  push: 
    branches: 
      - main

env: 
  SOLUTION_PATH: ./CryptoAPI.sln

jobs: 

   
  CD-Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        env:
         DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
         DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          
      - name: Docker Build CD
        run: |
          docker build -t dutchones/cryptoapi:v1
        
      - name: Docker Push
        run: |
          docker push dutchones/cryptoapi:v1
