name: .NET_API_CI_CD

on:
  push: 
    branches: 
      - main

env: 
  SOLUTION_PATH: ./CryptoAPI.sln

jobs: 

   
  CD-Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Docker Build CD
        run: |
          docker build ./CryptoAPI.sln -t dutchones/cryptoapi:v1
        
      - name: Docker Push
        run: |
          docker push dutchones/cryptoapi:v1
